# -*- coding: utf-8 -*-
"""Cópia de Aula Introdução Python - local.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r1VsI5wE8Z1zzU0OmTKeUuug7B7w84k8

#Imprimindo - Descoberta guiada

Imprima o texto meu primeiro código usando a função print:
"""

print("Meu primeiro código usando a função print")

"""#Imprimindo - Hands-on

Imprima o seu nome usando a função print:
"""

print("Hallan")

nome = input("Informe seu nome")
texto1 = "Seu nome é "
texto2 = ": "

print(texto1 + texto2 + nome)
print("Seu nome é " + texto2 + nome)

"""#Variáveis - Descoberta guiada

Armazene o dia, mês e ano em que nasceu

dia = 11
mes = 3
ano = 1992

print("dia: ", dia , "\nmes", mes)
print("ano:", ano)

"""#Variáveis - Hands on

Armazene a quantidade de lâmpadas na sala e imprima na tela essas informações.
"""

lampada = 8
print("lampadas totais",lampada)

"""Armazene seu nome e a cidade onde você nasceu e imprima usando a função print."""

nome = "Alan"
cidade = "campo grande"
print("seu nome",nome)
print("cidade onde nasceu",cidade)

"""#Operadores matemáticos - Descoberta guiada

Considerando que uma lâmpada gasta em

---

média 6 kw/h, ficando ligada em média 2hrs por dia por 20 dias. E o valor pago por cada kw/h
é de R$ 0,57 centavos. Quanto estamos gastando por mês com as lâmpadas da sala?
"""

lampadas = 8
kw_h = 6
tempo = 2 * 20
valor = 0.57

total = lampadas * tempo * kw_h * valor

print(total)

"""#Operadores matemáticos - Hands on

Se trocassemos as lâmpadas por outras mais econômicas de 4 kw/h, de quanto seria a economia?
"""

lampadas = 8
kw_h = 6
kw_h_novo = 4
tempo = 2 * 20
valor = 0.57

total = lampadas * tempo * kw_h * valor
total_novo = lampadas * tempo * kw_h_novo * valor

print("diferença = ",  round(total - total_novo, 2))

"""Maria tinha uma quantia, gastou 25% e ainda ficou com R$ 197,50. Qual o valor que Maria tinha inicialmente?"""

restante = 197.50
porcentagem = 0.75

print(restante / porcentagem)

"""Considerando o ano que você nasceu que foi armazenado em uma variável,atualmente você tem quantos anos?"""

ano_nascimeto = 1992
ano_atual = 2025

idade = ano_atual - ano_nascimeto

print(idade)

"""#Cast - Descoberta guiada

Imprima a sua idade, gerada no exercício anterior junto com o descritivo.

Ex.: A idade é de 45 anos.
"""

ano_nascimeto = 1992
ano_atual = 2025

idade = ano_atual - ano_nascimeto
descritivo = "A idade é de " + str(idade) + " anos"
print(descritivo)

"""#Cast - Handas on

Receba o ano de nascimento através de input e retorno a idade da pessoa.
"""

ano_atual = 2025
ano_nascimeto = int(input("Qual é o seu ano de nascimento? "))

print("A sua idade é: ", ano_atual - ano_nascimeto)

"""Crie um código que permita inserir a quantidade de lâmpadas, consumo médio em kw/h, quantidade de horas por dia e dias por mês e retorne o valor da conta (considerando R$ 0,57)."""

lampadas = int(input("Qual é a quantidade de lâmpadas? "))
kw_h = int(input("Qual é o consumo da lâmpada? "))
horas = int(input("Qual é a quantidade de horas por dia? "))
dias = int(input("Qual é a quantidade de dias? "))
tempo_total_em_horas = horas * dias
valor = 0.57

total = lampadas * tempo_total_em_horas * kw_h * valor

print("O valor da sua conta é:", total)

"""#IF - Descoberta guiada

Colete a idade com um input e imprima na tela a palavra "Acima de 30" somente se a idade for maior que 30.
"""

print("Essa calculadora serve converter de graus celsius para kelvin.")
print("Informe a letra k para converter de celsius para kelvin ou c para o contrario")
# esse linha abaixo recebe a letra com a opção do usuário
operacao = input("Informe k ou c ")
if operacao == "k":
  temperatura = input("informe a temperatura e graus celsius")
  temperatura_kelvin = float(temperatura) + 273
  print("A temperatura em kelvin é: ", temperatura_kelvin)
else:
  if operacao == "c":
    temperatura = input("informe a temperatura e kelvin")
    temperatura_kelvin = float(temperatura) - 273
    print("A temperatura em graus celsius é: ", temperatura_kelvin)
  else:
    print("Opção invalida")

"""#IF - Hands on

Imprima a palavra abaixo de 20 anos, caso seja verdadeiro.
"""

idade = int(input("insira sua idade:"))
if idade <= 20 :
  print("verdadeiro")
else:
  print(False)

"""Faça uma calculadora que converta graus Celsius para Kelvin e Vice versa de acordo com o valor que o usuário inseriu no input e a letra para qual ele quer transformar (C ou K)"""

# Solicita o valor da temperatura
valor = float(input("Digite a temperatura: "))

# Solicita para qual unidade deseja converter
alvo = input("Digite 'C' para converter para Celsius ou 'K' para converter para Kelvin: ")

# Conversão com estrutura if
if alvo == 'C' or alvo == 'c':
    resultado = valor - 273.15
    print(f"{valor}K é igual a {resultado:.2f}°C")

if alvo == 'K' or alvo == 'k':
    resultado = valor + 273.15
    print(f"{valor}°C é igual a {resultado:.2f}K")

# Tratamento simples de entrada inválida
if alvo != 'C' and alvo != 'c' and alvo != 'K' and alvo != 'k':
    print("Unidade de conversão inválida. Use 'C' ou 'K'.")

"""#IF ELSE - Descoberta guiada

Crie a calculadora que alculadora que converta graus Celsius para Kelvin e Vice versa de acordo com o valor que o usuário inseriu no input e a letra para qual ele quer transformar (C ou K), porém se o valor inserido não for nem C nem K, avise o usuário que o tipo inserido está incorreto.
"""

# Solicita o valor da temperatura
valor = float(input("Digite a temperatura: "))

# Solicita o tipo de conversão
tipo = input("Digite 'C' para converter para Celsius ou 'K' para converter para Kelvin: ")

# Conversão com if e else
if tipo == 'C' or tipo == 'c':
    resultado = valor - 273.15
    print(f"{valor}K é igual a {resultado:.2f}°C")
else:
    if tipo == 'K' or tipo == 'k':
        resultado = valor + 273.15
        print(f"{valor}°C é igual a {resultado:.2f}K")
    else:
        print("Tipo inserido incorreto. Por favor, use 'C' ou 'K'.")

estado = input("estado")
if estado == "RS" or estado == "SC" or estado == "PR":
  print("voce mora no Sul")
else:
  print("voce não mora no sul ")

"""#IF ELSE - Hands on

Crie uma calculadora que converta cm em metros e vice versa de acordo com o inout que o usuário insere (cm / m). Se o calor inserido não for nenhum dos dois, avise o usuário que o tipo inserido está incorreto.
"""

# Solicita o valor numérico
valor = float(input("Digite o valor que deseja converter: "))

# Solicita o tipo de conversão
tipo = input("Digite 'cm' para converter de metros para centímetros ou 'm' para converter de centímetros para metros: ")

# Conversão com if e else
if tipo == 'cm' or tipo == 'CM':
    resultado = valor * 100
    print(f"{valor} metros é igual a {resultado:.2f} centímetros.")
else:
    if tipo == 'm' or tipo == 'M':
        resultado = valor / 100
        print(f"{valor} centímetros é igual a {resultado:.2f} metros.")
    else:
        print("Tipo inserido incorreto. Por favor, use 'cm' ou 'm'.")

